

```{r, variable names}
data_names <- c(
     "year",
     "type",
     "county",
     "prec",
     "office_code",
     "district",
     "party_code",
     "ballot_pos",
     "office",
     "party",
     "cand_num",
     "last",
     "first",
     "middle",
     "suffix",
     "vote",
     "yes",
     "no",
     "cong_dist",
     "sen_dist",
     "house_dist",
     "muni_type",
     "muni_name",
     "muni_breakdown_code_1",
     "muni_breakdown_name_1",
     "muni_breakdown_code_2",
     "muni_breakdown_name_2",
     "bicounty_code",
     "mcd",
     "fips",
     "vtd",
     "ballot_question",
     "record_type",
     "prev_prec_code",
     "prev_cong_dist",
     "prev_sen_dist",
     "prev_house_dist"
)
```

```{r, name=Functions}
source("https://raw.githubusercontent.com/jcervas/R-Functions/main/GERRYfunctions.R")
source("https://raw.githubusercontent.com/jcervas/R-Functions/main/sv-hyp.R")

### Not sure whate `replace_values` did, so making an empty function
replace_values <- function(x) {x}
```

```{r}
## https://www.dos.pa.gov/VotingElections/BEST/stats/_layouts/15/formspubs/formsandpubs.aspx
PA_g22 <- read.csv("https://www.dos.pa.gov/VotingElections/BEST/stats/Documents/ElectionReturns_2022_General_PrecinctReturns.txt", header=FALSE, stringsAsFactors=FALSE)
names(PA_g22) <- data_names
```

```{r}
g22 <- PA_g22

g22$GEOID20 <- paste0(42,leadingZeroes(g22$fips,3), substrRight(paste0("000000",g22$prec),6))
  length(unique(g22$GEOID20))

g22_reduced <- g22[names(g22) %in% c("fips", "GEOID20", "office", "party", "last", "prec", "cong_dist", "house_dist", "sen_dist", "vote", "muni_name")]
  head(g22_reduced)
```


```{r}
## collect election results wide by race/district
  ## house_dist, sen_dist, cong_dist
    elect_collect <- function(x,variable=NA) {
        if(is.na(variable)){stop("choose a variable to aggregate on.")}
      DEM <- subset(x, (party=="DEM"))
      GOP <- subset(x, (party=="REP"))
      OTH <- subset(x, (!party %in% c("DEM","REP")))

      tmp.dem <- aggregate(list(dem=DEM[,"vote"]), by=list(district=DEM[,variable]), FUN=sum)
      tmp.gop <- aggregate(list(gop=GOP[,"vote"]), by=list(district=GOP[,variable]), FUN=sum)
      tmp.oth <- aggregate(list(oth=OTH[,"vote"]), by=list(district=OTH[,variable]), FUN=sum)

      out <- merge(tmp.dem,tmp.gop, by="district", all = TRUE)
      out <- merge(out,tmp.oth, by="district", all = TRUE)
      out <- replaceNA(out)
      return(out)
    }
```



Seat Shares
```{r}
offices <- c("USS", "GOV", "USC", "STH", "STS")
agg_type <- c("house_dist", "sen_dist", "cong_dist")

per <- function(x) paste0(round(x*100,1),"%")

for (i in offices) {
  tmp <- subset(g22_reduced, (office==i))
  assign(i, tmp)
  print(i)
    for (j in agg_type) {
    j_tmp <- elect_collect(tmp, j)
      j_tmp$DEMtp <- replace_values(two_party(j_tmp$dem,j_tmp$gop))
      j_tmp$dem_vote <- j_tmp$dem/(j_tmp$dem+j_tmp$gop+j_tmp$oth)
      j_tmp$gop_vote <- j_tmp$gop/(j_tmp$dem+j_tmp$gop+j_tmp$oth)
    tmp_j <- assign(paste0(i,"_",j),j_tmp)
    print(paste0(i,"_",j))
    print(paste0("Votes: ", per(mean(j_tmp$DEMtp))))
    print(paste0("Seats: ", sum(1 * (j_tmp$DEMtp > 0.5)), "D-", sum(1 * (j_tmp$DEMtp < 0.5)),"R (", per(mean(1 * (j_tmp$DEMtp > 0.5))),")"))
    write.csv(tmp_j, paste0("/Users/cervas/My Drive/GitHub/Data/Elections/State Legislature/PA/data/",i,"_",j,".csv"), row.names=F)
    }
}

```

Two Party Statewide Vote Share
```{r}
# PA House
house_seats_votes <- array(NA, c(5, 3))
n <- 1
for (i in offices) {
  tmp <- subset(g22_reduced, (office==i))
  statewide <- elect_collect(tmp, "house_dist")

  dem <- mean(replace_values(two_party(statewide$dem, statewide$gop)))
  gop <- mean(replace_values(two_party(statewide$gop, statewide$dem)))
print(paste0(i, " D-", per(dem), " R-", per(gop)))

house_seats_votes[n,1] <- i
house_seats_votes[n,2] <- dem
house_seats_votes[n,3] <- sum(1 * (replace_values(two_party(statewide$dem, statewide$gop)) > 0.5))/length(two_party(statewide$dem, statewide$gop))
n <- n+1
}

# PA Senate
senate_seats_votes <- array(NA, c(5, 3))
n <- 1
for (i in offices) {
  tmp <- subset(g22_reduced, (office==i))
  statewide <- elect_collect(tmp, "sen_dist")

  dem <- mean(replace_values(two_party(statewide$dem, statewide$gop)))
  gop <- mean(replace_values(two_party(statewide$gop, statewide$dem)))
print(paste0(i, " D-", per(dem), " R-", per(gop)))

senate_seats_votes[n,1] <- i
senate_seats_votes[n,2] <- dem
senate_seats_votes[n,3] <- sum(1 * (replace_values(two_party(statewide$dem, statewide$gop)) > 0.5)/length(two_party(statewide$dem, statewide$gop)))
n <- n+1
}

house_seats_votes
senate_seats_votes

```

Plot S/V curves for actual election results
```{r}
seatsvotes.plot(main="PA House of Representatives", prop.line=FALSE)
points(house_seats_votes[,2:3], pch=16)
sv_curve(as.numeric(house_seats_votes[,3]), as.numeric(house_seats_votes[,2]), lwd=3, col="gray70")

seatsvotes.plot(main="PA Senate", prop.line=FALSE)
points(senate_seats_votes[,2:3], pch=17)
sv_curve(as.numeric(senate_seats_votes[,3]), as.numeric(senate_seats_votes[,2]), lwd=3, col="gray70")

```


S/V curves for simulated elections

Setup
```{r}

v_s_sim <- function(data, range_sim=seq(-0.1,0.1,0.01)) {
range_sim <- ifelse(is.na(range_sim), seq(-0.1,0.1,0.01), range_sim)
n <- length(range_sim)
votes_seats <- cbind(rep(NA, n), rep(NA,n))
colnames(votes_seats) <- c("votes","seats")
rownames(votes_seats) <- range_sim

  for (i in 1:n) {
    tmp <- data + range_sim[i]
    seats_tmp <- prop.table(table(1 * (tmp > 0.5)))
    votes_seats[i,1] <- mean(tmp)
    votes_seats[i,2] <- seats_tmp[2]
  }
  return(votes_seats)
}

bias <- responsiveness <- array(NA, c(5, 2))

```

PA House of Representatives
```{r}
seatsvotes.plot(main="PA House of Representatives", prop.line=F)

datasets_house <- list(STH_house_dist,STS_house_dist,USS_house_dist, GOV_house_dist, USC_house_dist)

datasets_senate <- list(STH_sen_dist,STS_sen_dist,USS_sen_dist, GOV_sen_dist, USC_sen_dist)

v_vals <- s_vals <- c()
mean_v <- mean_s <- c()

for (i in 1:length(datasets_house)) {
  dataset <- as.data.frame(datasets_house[i])
  v_s <- v_s_sim(dataset$DEM)
  v <- v_s[, 1]
  s <- v_s[, 2]

  mean_v <- c(mean_v, mean(dataset$DEM))
  mean_s <- c(mean_s, mean(find.winner(dataset$DEM)))

  sv_curve(s, v, lwd = 0.5, col = "gray30")

  v_vals <- c(v_vals, v)
  s_vals <- c(s_vals, s)
  bias[i,1] <- sv_bias(s,v)
  responsiveness[i,1] <- sv_responsiveness(s,v)
}

seatsvotes.plot()
points(v_s_sim(STH_house_dist$DEM))

```

PA Senate
```{r}
seatsvotes.plot(main="PA Senate")

datasets_senate <- list(USS_sen_dist, GOV_sen_dist, STS_sen_dist, USC_sen_dist, STH_sen_dist)

v_vals <- s_vals <- c()
mean_v <- mean_s <- c()

for (i in 1:length(datasets_senate)) {
  dataset <- as.data.frame(datasets_senate[i])
  v_s <- v_s_sim(dataset$DEM)
  v <- v_s[, 1]
  s <- v_s[, 2]

  mean_v <- c(mean_v, mean(dataset$DEM))
  mean_s <- c(mean_s, mean(find.winner(dataset$DEM)))

  sv_curve(s, v, lwd = 0.5, col = "gray30")

  v_vals <- c(v_vals, v)
  s_vals <- c(s_vals, s)
  bias[i,2] <- sv_bias(s,v)
  responsiveness[i,2] <- sv_responsiveness(s,v)
}


colMeans(bias)
colMeans(responsiveness)

```





